[tool.poetry]
name = "do-some"
version = "0.1.0"
description = ""
authors = ["Kuragin Vanya <curagin.vanya@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
